### ISSUE TITLE
wrong commit returned if there are lots of commits

### ISSUE THREAD

**Issue by timotheecour** [ActionsRML/get-PR-latest-commit#5]
in a PR that has lots of commits (but definitely less than 100, see below), it doesn't return the last commit, but some arbitrary intermediate commit.

## note
looking at https://github.com/ActionsRML/get-PR-latest-commit/blob/master/dist/index.js which lists https://octokit.github.io/rest.js/v18#pulls-list-commits it shows:

> Lists a maximum of 250 commits for a pull request. To receive a complete commit list for pull requests with more than 250 commits, use the List commits endpoint.

and this:
> per_page | no | Results per page (max 100)

I'm wondering if by default it truncates / paginates earlier than 100 if per_page isn't specified

This matters because logic based on 
```
if: contains(steps.get-latest-commit.outputs.latest_commit_message, '[ci skip]')
```

could be wrong

## EDIT
* seems to give this bug for number of commits around 35, perhaps less

## alternative without this package
* ended up using instead:
```
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: get commit message
        run: echo $(git log --format=%B -n 1 ${{ github.event.after }})
```
